api:
  auth: ""
  max_num_block_files: 1000
  max_num_blocks: 50
  num_workers: 10
  streaming_batch_size: 50
  streaming_interval: 1s
  streaming_max_no_event_time: 10m
  rate_limit:
    global_rps: 3000
    per_client_rps: 2000
aws:
  aws_account: development
  bucket: ""
  dlq:
    delay_secs: 900
    name: example_chainstorage_blocks_{{blockchain}}_{{network}}_dlq
    visibility_timeout_secs: 600
  dynamodb:
    block_table: example_chainstorage_blocks_{{blockchain}}_{{network}}
    versioned_event_table: example_chainstorage_versioned_block_events_{{blockchain}}_{{network}}
    versioned_event_table_block_index: example_chainstorage_versioned_block_events_by_block_id_{{blockchain}}_{{network}}
    transaction_table: example_chainstorage_transactions_table_{{blockchain}}_{{network}}
  presigned_url_expiration: 30m
  region: us-east-1
  storage:
    data_compression: GZIP
gcp:
  project: "development"
  presigned_url_expiration: 30m
cadence:
  address: ""
  retention_period: 7
  domain: chainstorage-{{blockchain}}-{{network}}
  tls:
    enabled: true
    validate_hostname: true
chain:
  block_start_height: 0
  blockchain: BLOCKCHAIN_{{BLOCKCHAIN}}
  client:
    master:
      endpoint_group: ""
    slave:
      endpoint_group: ""
    validator:
      endpoint_group: ""
    consensus:
      endpoint_group: ""
    http_timeout: 0s
  network: NETWORK_{{BLOCKCHAIN}}_{{NETWORK}}
  block_tag:
    latest: 1
    stable: 1
  event_tag:
    latest: 1
    stable: 1
  feature:
    rosetta_parser: false
    default_stable_event: true
config_name: "{{blockchain}}_{{network}}"
cron:
  block_range_size: 4
functional_test: ""
sdk:
  auth_header: ""
  auth_token: ""
  chainstorage_address: "https://example-chainstorage-{{blockchain}}-{{network}}"
  num_workers: 10
  restful: true
server:
  bind_address: "localhost:9090"
sla:
  tier: 3
  expected_workflows:
    - monitor
    - poller
    - streamer
workflows:
  backfiller:
    activity_retry_maximum_attempts: 3
    activity_schedule_to_start_timeout: 5m
    activity_start_to_close_timeout: 10m
    batch_size: 2500
    checkpoint_size: 5000
    max_reprocessed_per_batch: 30
    mini_batch_size: 1
    num_concurrent_extractors: 4
    task_list: default
    workflow_decision_timeout: 2m
    workflow_execution_timeout: 24h
    workflow_identity: workflow.backfiller
  benchmarker:
    activity_retry_maximum_attempts: 3
    activity_schedule_to_start_timeout: 5m
    activity_start_to_close_timeout: 10m
    child_workflow_execution_start_to_close_timeout: 60m
    task_list: default
    workflow_decision_timeout: 2m
    workflow_execution_timeout: 24h
    workflow_identity: workflow.benchmarker
  monitor:
    activity_retry_maximum_attempts: 8
    activity_schedule_to_start_timeout: 5m
    activity_start_to_close_timeout: 10m
    backoff_interval: 10s
    batch_size: 50
    checkpoint_size: 500
    parallelism: 4
    block_gap_limit: 3000
    event_gap_limit: 300
    task_list: default
    workflow_decision_timeout: 2m
    workflow_execution_timeout: 24h
    workflow_identity: workflow.monitor
  poller:
    activity_heartbeat_timeout: 2m
    activity_retry_maximum_attempts: 8
    activity_schedule_to_start_timeout: 2m
    activity_start_to_close_timeout: 10m
    backoff_interval: 3s
    checkpoint_size: 1000
    fast_sync: false
    liveness_check_enabled: true
    liveness_check_interval: 1m
    liveness_check_violation_limit: 10
    max_blocks_to_sync_per_cycle: 100
    parallelism: 4
    task_list: default
    workflow_decision_timeout: 2m
    workflow_execution_timeout: 24h
    session_creation_timeout: 2m
    session_enabled: false
    workflow_identity: workflow.poller
  streamer:
    activity_retry_maximum_attempts: 5
    activity_schedule_to_start_timeout: 2m
    activity_start_to_close_timeout: 2m
    backoff_interval: 3s
    batch_size: 500
    checkpoint_size: 500
    task_list: default
    workflow_decision_timeout: 2m
    workflow_execution_timeout: 24h
    workflow_identity: workflow.streamer
  cross_validator:
    activity_retry_maximum_attempts: 8
    activity_schedule_to_start_timeout: 5m
    activity_start_to_close_timeout: 10m
    backoff_interval: 10s
    batch_size: 100
    checkpoint_size: 1000
    parallelism: 4
    task_list: default
    validation_percentage: 10
    workflow_decision_timeout: 2m
    workflow_execution_timeout: 24h
    workflow_identity: workflow.cross_validator
  event_backfiller:
    activity_retry_maximum_attempts: 3
    activity_schedule_to_start_timeout: 5m
    activity_start_to_close_timeout: 10m
    batch_size: 250
    checkpoint_size: 5000
    task_list: default
    workflow_decision_timeout: 2m
    workflow_execution_timeout: 24h
    workflow_identity: workflow.event_backfiller
  replicator:
    activity_retry_maximum_attempts: 5
    activity_schedule_to_start_timeout: 5m
    activity_start_to_close_timeout: 10m
    batch_size: 1000
    mini_batch_size: 100
    checkpoint_size: 10000
    parallelism: 10
    task_list: default
    workflow_decision_timeout: 2m
    workflow_execution_timeout: 24h
    workflow_identity: workflow.replicator
  workers:
    - task_list: default
