aws:
  aws_account: development
  bucket: example-chainstorage-{{blockchain}}-{{network}}-{{short_env}}
cadence:
  address: temporal-dev.example.com:7233
workflows:
  poller:
    activity_retry_maximum_attempts: 6
    activity_schedule_to_start_timeout: 5m
  streamer:
    activity_schedule_to_start_timeout: 5m
server:
  bind_address: "0.0.0.0:9090"
