aws:
  aws_account: development
  storage:
    data_compression: GZIP
chain:
  block_time: 13s
  event_tag:
    latest: 0
    stable: 0
  irreversible_distance: 14
  feature:
    rosetta_parser: true
sla:
  block_height_delta: 40
  block_time_delta: 10m
  out_of_sync_node_distance: 40
  tier: 1
  time_since_last_block: 15m
  expected_workflows:
    - monitor
    - poller
    - streamer
    - datalake/block_tag=1
workflows:
  backfiller:
    num_concurrent_extractors: 24
  poller:
    backoff_interval: 10s
    failover_enabled: true
  streamer:
    backoff_interval: 10s
  monitor:
    failover_enabled: true
