chain:
  block_time: 500ms
  event_tag:
    latest: 1
    stable: 1
sla:
  block_height_delta: 200
  block_time_delta: 1m30s
  out_of_sync_node_distance: 200
  tier: 2
  time_since_last_block: 2m
  expected_workflows:
    - monitor
    - poller
    - streamer/event_tag=1
workflows:
  backfiller:
    num_concurrent_extractors: 300
  monitor:
    backoff_interval: 1s
