package types

type TraceType int

const (
	TraceType_UNKNOWN TraceType = iota
	TraceType_GETH
	// TODO: Remove if necessary based on the result of this issue https://github.com/ledgerwatch/erigon/issues/4935.
	TraceType_ERIGON
	TraceType_PARITY
)

// ErigonTraceEnabled returns true if the traces are generated by an Erigon client. Erigon format is similar to GETH,
// but the trace objects not individually keyed with "result" in the final array.
func (t TraceType) ErigonTraceEnabled() bool {
	return t == TraceType_ERIGON
}

func (t TraceType) ParityTraceEnabled() bool {
	return t == TraceType_PARITY
}
