api:
  streaming_interval: 250ms
aws:
  aws_account: development
  storage:
    data_compression: GZIP
chain:
  block_time: 400ms
  event_tag:
    latest: 0
    stable: 0
cron:
  disable_dlq_processor: true
sla:
  block_height_delta: 150
  block_time_delta: 1m30s
  out_of_sync_node_distance: 150
  tier: 2
  time_since_last_block: 3m
  expected_workflows:
    - monitor
    - poller
    - streamer
workflows:
  backfiller:
    num_concurrent_extractors: 64
  monitor:
    backoff_interval: 1s
    batch_size: 25
    parallelism: 10
  poller:
    backoff_interval: 500ms
    fast_sync: true
    max_blocks_to_sync_per_cycle: 300
    parallelism: 24
    session_enabled: true
  streamer:
    backoff_interval: 500ms
