aws:
  aws_account: development
chain:
  block_start_height: 80000000
sla:
  block_height_delta: 1000
  block_time_delta: 10m
  out_of_sync_node_distance: 1000
  tier: 2
  time_since_last_block: 15m
workflows:
  backfiller:
    num_concurrent_extractors: 48
