chain:
  block_time: 1m
  event_tag:
    latest: 0
    stable: 0
  rosetta:
    blockchain: dogecoin
    network: mainnet
    block_not_found_error_codes: 4
  feature:
    rosetta_parser: true
aws:
  aws_account: development
  storage:
    data_compression: GZIP
cron:
  disable_dlq_processor: true
sla:
  block_height_delta: 5
  block_time_delta: 30m
  out_of_sync_node_distance: 10
  tier: 2
  time_since_last_block: 1h
  expected_workflows:
    - monitor
    - poller
    - streamer
    - datalake/block_tag=1
workflows:
  backfiller:
    num_concurrent_extractors: 24
  poller:
    backoff_interval: 10s
    parallelism: 10
  streamer:
    backoff_interval: 10s
